### ISSUE TITLE
Install fails on python 3.9

### ISSUE THREAD

**Issue by icfly2** [aleaxit/gmpy#295]
I'm trying to install gmpy2 on a pthon:3.9-buster docker image. this fails with the below error:

```
root@bb28e26c1126:/src/python# pip install gmpy2
Looking in indexes: https://pypi.org/simple, https://internal_pypi:****@pkgs.dev.azure.com/banking-circle-payment-systems/_packaging/internal_pypi/pypi/simple
Collecting gmpy2
  Downloading https://pkgs.dev.azure.com/****/_packaging/28ebd5ed-b704-4485-9dd7-0b6f0c6c6ff2/pypi/download/gmpy2/2.0.8/gmpy2-2.0.8.zip (280 kB)
     |████████████████████████████████| 280 kB 5.0 MB/s 
Building wheels for collected packages: gmpy2
  Building wheel for gmpy2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-siw0byk3
       cwd: /tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'gmpy2' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITHMPFR -DWITHMPC -I/usr/local/include/python3.7m -c src/gmpy2.c -o build/temp.linux-x86_64-3.7/src/gmpy2.o
  In file included from src/gmpy2.c:426:
  src/gmpy.h:252:12: fatal error: mpfr.h: No such file or directory
   #  include "mpfr.h"
              ^~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for gmpy2
  Running setup.py clean for gmpy2
Failed to build gmpy2
Installing collected packages: gmpy2
    Running setup.py install for gmpy2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-y6ba69om/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/gmpy2
         cwd: /tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/
    Complete output (14 lines):
    running install
    running build
    running build_ext
    building 'gmpy2' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITHMPFR -DWITHMPC -I/usr/local/include/python3.7m -c src/gmpy2.c -o build/temp.linux-x86_64-3.7/src/gmpy2.o
    In file included from src/gmpy2.c:426:
    src/gmpy.h:252:12: fatal error: mpfr.h: No such file or directory
     #  include "mpfr.h"
                ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-edjqgswx/gmpy2_a0b89d8ed6d24c8fa662f08fc82b5e6b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-y6ba69om/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/gmpy2 Check the logs for full command output.
```

What is the latest version of python that gmpy2 works on? or what could be the issue here. I'll try and debug my self later, but this is not my area of expertise.

**Comment by casevh** [comment]
Most likely solution is installing libmpc-dev package. Let me know if that doesn't work.

**Comment by skirpichev** [comment]
@casevh, gmpy2 builds fine on 3.9, e.g. [here](https://github.com/diofant/diofant/runs/2091985576).

But I think, that it worth mention supported (and/or tested) CPython versions somewhere in the docs.

**Comment by casevh** [comment]
@skirpichev I test gmpy2 on Python 2.7 and 3.5 to 3.10. Almost all the reports of installation errors are due to missing OS dependencies (i.e. the development files for GMP, MPFR, and MPC).

@icfly2 Were you able to resolve the issue?

**Comment by skirpichev** [comment]
@casevh, probably this can be closed?

Or we should do something more, e.g. we could add several python versions to the build matrix in pip_install_gmpy2.yml?

**Comment by casevh** [comment]
Closing. No practical method to specify OS dependencies.
