### PR TITLE
Fix issue #189

### PR DESCRIPTION
**Pull request by vinklein**
With the current of setup.py the cython interface don't work.

setup.py :
- Remove gmpy2.gmpy2 package.
- Delete gmpy/gmpy2 directory
- Have file gmpy.h, gmpy2.pyx and gmpy2.h installed under sites-packages and not under sites-packages/gmpy2.

.travis.yml :
Don't use apt-get install to install cython. In current version cython is not detected by the test_cython/runtest.py script and cython tests are always skipped

Linked to issue #189

### CODE REVIEW

**Comment by casevh** [comment]
@pkittenis 

Can you comment on this pull request and issue #189? I believe this is related to your changes in issue #178.

casevh

**Comment by vinklein** [comment]
From my tests the cython interface is broken by #178 merge. It will be good to do a `python test_cython/runtest.py` when doing change on the cython interface.

**Comment by pkittenis** [comment]
These changes revert everything done to make gmpy2 a python package. This breaks tools and use cases which require a python package, binary wheels with dynamic linking most important one.

Furthermore, Installing library headers as `data_files` is problematic. It means they will be installed under `site-packages/src/..` and will not be found under the package's install directory. So cython C level imports (`#include <..>/gmpy2.h`) will not be able to find the headers under the gmpy2 package directory.

On a lesser note, it is considered bad practice to install package files like headers as data files. The `gmpy2_install_data` stuff does not look correct for binary wheel installations either and I'm not sure setting install dir as if the package was pure python is correct either.

If the cython cimports are not working, let's fix that. The existing `__init__.pxd` was attempting to do that. 

`test_cython/runtests.py` fails with the old setup.py as well (`AttributeError: 'module' object has no attribute '_C_API'`) for me, so what is the output supposed to be from that script?

The issues seems to be that the `from gmpy cimport *` line in `__init__.pxd` is not being picked up, so the extension is only available under `gmpy2.gmpy2`. That is an easy fix:

`from gmpy2.gmpy2 cimport *` in `__init__.pxd`

Now works the same as before, as in I get same error as `setup_legacy.py` -- 

```
from gmpy2 cimport *
import_gmpy2()
```

```AttributeError: 'module' object has no attribute '_C_API'```

I will raise a PR for the above change.

It would also be good to include `test_cython/runtests.py` in the automated tests. All the automated testing passed with the #178 changes, so this regression was never picked up.

**Comment by vinklein** [comment]
> These changes revert everything done to make gmpy2 a python package. This breaks tools and use cases which require a python package, binary wheels with dynamic linking most important one.
> 
> Furthermore, Installing library headers as data_files is problematic. It means they will be installed under site-packages/src/.. and will not be found under the package's install directory. So cython C level imports (#include <..>/gmpy2.h) will not be able to find the headers under the gmpy2 package directory.
> 
> On a lesser note, it is considered bad practice to install package files like headers as data files. The gmpy2_install_data stuff does not look correct for binary wheel installations either and I'm not sure setting install dir as if the package was pure python is correct as well.
> 
> If the cython cimports are not working, let's fix that. The existing __init__.pxd was attempting to do that.

I agree this will be all the better if it work with gmpy2 as a package. We juste didn't manage to do that.

> test_cython/runtests.py fails with the old setup.py as well (AttributeError: 'module' object has no attribute '_C_API') for me, so what is the output supposed to be from that script?

These tests works if you test with the revision before the merge of #178
```
git -c core.quotepath=false checkout 4ea92ab8542d79c4c771ea18c6553244ac318a6a --
...
pip install . --user
... 
python test_cython/runtest.py
()
Unit tests for gmpy2 2.1.0a1 with Cython 0.28.2
()
Compiling test_cython.pyx because it changed.
[1/1] Cythonizing test_cython.pyx
warning: /home/vklein/.local/lib/python2.7/site-packages/gmpy2.pxd:45:4: 'mpfr_prec_t' redeclared 
running build_ext
building 'test_cython' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/vklein/.local/lib/python2.7/site-packages -I/tmp/tmpE6oetT -I/usr/lib/python2.7 -I/usr/lib/python2.7/plat-x86_64-linux-gnu -I/usr/lib/python2.7/lib-tk -I/usr/lib/python2.7/lib-old -I/usr/lib/python2.7/lib-dynload -I/usr/local/lib/python2.7/dist-packages -I/usr/lib/python2.7/dist-packages -I/usr/lib/python2.7/dist-packages/gtk-2.0 -I/usr/include/python2.7 -c test_cython.c -o build/temp.linux-x86_64-2.7/test_cython.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_cython.o -lgmp -lmpfr -lmpc -o /tmp/tmpE6oetT/test_cython.so
test_check... pass
test_mpc... pass
test_mpc_cmp... pass
test_mpc_from_mpc... pass
test_mpc_from_mpfr... pass
test_mpfr... pass
test_mpfr_cmp... pass
test_mpfr_from_mpfr... pass
test_mpq... pass
test_mpq_cmp... pass
test_mpq_from_mpq... pass
test_mpq_from_mpz... pass
test_mpz... pass
test_mpz_cmp... pass
test_mpz_from_mpz... pass
test_py_check... pass
All tests pass!
```

> I will raise a PR for the above change.
> 
> It would also be good to include test_cython/runtests.py in the automated tests. 

They are in travis.yml, they just used to be skipped because cython was not detected by runtest.py. 
This is fixed in this PR. You can look at the diff of .travis.yml.

**Comment by casevh** [comment]
I've looked a little at the issue with the missing _C_API. It is failing due to the `from .gmpy import *`  hack. The name does not appear to be imported. If I do `import gmpy2.gmpy2`, I can see `_C_API` in `dir(gmpy2.gmpy2`).

More comments later; I am out of time.

**Comment by vinklein** [comment]
Ok it is sure that it would be cleaner with a package version.

**Comment by pkittenis** [comment]
IIRC, internal functions are not imported by wild card imports, so `_C_API` is skipped. The `_` prefix marks it as internal. It is one of the reasons wild card imports are considered bad practice.

Would suggest making the name `C_API` if it is to be used from outside the module. Can make that change as part of #191 if you'd like, is only used in the `import_gmpy2` python function and defined in `gmpy2.c`.

**Comment by casevh** [comment]
So the wildcard import also will break mpmath support since there are several mpmath helper functions that begin with _.

Are there any alternatives to the wildcard import? Modifying sys.modules?

**Comment by pkittenis** [comment]
| Are there any alternatives to the wildcard import?

Explicit imports will work fine and is the recommended approach. The down side is any additions to code will need to be added to `__init__.py` as well, but any new public functions/variables should not be starting with `_` in any case.

Are the helper functions used in client code? How come they are marked as internal?

**Comment by casevh** [comment]
I'm fine with adding explicit imports for _C_API and the _mpmath* helper functions.

The _mpmath* helper functions are intended to replace a few specific internal functions in mpmath. They have very specific parameter requirements and are not really useful for any other purpose. I don't see any advantage to changing the names. I doubt any more mpmath functions will be created.

**Comment by pkittenis** [comment]
See [191 PR](https://github.com/aleaxit/gmpy/pull/191#issuecomment-382441223).

**Comment by vinklein** [comment]
Ok all is fixed with PR #191. I will do another PR for the travis modification alone
